find_package(Pangolin REQUIRED)
message("Pangolin Version:" ${Pangolin_VERSION})
include_directories(${Pangolin_INCLUDE_DIRS})
list(APPEND ALL_TARGET_LIBRARIES ${Pangolin_LIBRARIES} )
list(APPEND ALL_TARGET_LIBRARIES ${Pangolin_LIBRARIES} fmt)